[2025-03-31T00:03:55.973+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-03-31T00:03:56.007+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.create_tables manual__2025-03-26T13:33:39.761724+00:00 [queued]>
[2025-03-31T00:03:56.015+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.create_tables manual__2025-03-26T13:33:39.761724+00:00 [queued]>
[2025-03-31T00:03:56.016+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-03-31T00:03:56.043+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): create_tables> on 2025-03-26 13:33:39.761724+00:00
[2025-03-31T00:03:56.049+0000] {standard_task_runner.py:63} INFO - Started process 570 to run task
[2025-03-31T00:03:56.052+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'create_tables', 'manual__2025-03-26T13:33:39.761724+00:00', '--job-id', '129', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpg3oyhzzh']
[2025-03-31T00:03:56.054+0000] {standard_task_runner.py:91} INFO - Job 129: Subtask create_tables
[2025-03-31T00:03:56.140+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_pipeline.create_tables manual__2025-03-26T13:33:39.761724+00:00 [running]> on host 7051e0ca121e
[2025-03-31T00:03:56.214+0000] {abstractoperator.py:725} ERROR - Exception rendering Jinja template for task 'create_tables', field 'sql'. Template: '/opt/***/dags/sql/create_table.sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/abstractoperator.py", line 717, in _do_render_template_fields
    rendered_content = self.render_template(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/template/templater.py", line 166, in render_template
    template = jinja_env.get_template(value)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/opt/airflow/dags/sql/create_table.sql' not found in search path: '/opt/airflow/dags'
[2025-03-31T00:03:56.216+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 2479, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 2633, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context, jinja_env=jinja_env)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3094, in render_templates
    original_task.render_template_fields(context, jinja_env)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 1337, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/abstractoperator.py", line 717, in _do_render_template_fields
    rendered_content = self.render_template(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/template/templater.py", line 166, in render_template
    template = jinja_env.get_template(value)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
jinja2.exceptions.TemplateNotFound: '/opt/airflow/dags/sql/create_table.sql' not found in search path: '/opt/airflow/dags'
[2025-03-31T00:03:56.228+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_pipeline, task_id=create_tables, run_id=manual__2025-03-26T13:33:39.761724+00:00, execution_date=20250326T133339, start_date=20250331T000356, end_date=20250331T000356
[2025-03-31T00:03:56.352+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 129 for task create_tables ('/opt/airflow/dags/sql/create_table.sql' not found in search path: '/opt/airflow/dags'; 570)
[2025-03-31T00:03:56.386+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-03-31T00:03:56.414+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-31T00:03:56.435+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
